# Generated by Django 5.2.1 on 2025-05-26 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed Parking Lot', max_length=255)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('video_path', models.CharField(blank=True, max_length=255, null=True)),
                ('data_path', models.CharField(blank=True, max_length=255, null=True)),
                ('start_frame', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parking Lot',
                'verbose_name_plural': 'Parking Lots',
            },
        ),
        migrations.CreateModel(
            name='ParkingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spaces', models.IntegerField(default=0)),
                ('free_spaces', models.IntegerField(default=0)),
                ('occupied_spaces', models.IntegerField(default=0)),
                ('unknown_spaces', models.IntegerField(default=0)),
                ('raw_statuses', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='parking_detection.parkinglot')),
            ],
            options={
                'verbose_name': 'Parking Status',
                'verbose_name_plural': 'Parking Statuses',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
